# Generated by Django 3.2 on 2022-04-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postlike',
            options={},
        ),
        migrations.AlterField(
            model_name='postlike',
            name='liked',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='postlike',
            table=None,
        ),
    ]
