# Generated by Django 3.2 on 2022-04-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_postlike_liked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postlike',
            options={'verbose_name': 'like', 'verbose_name_plural': 'likes'},
        ),
        migrations.AlterModelTable(
            name='postlike',
            table='postlike',
        ),
    ]
